### ISSUE TITLE
Content update roadmap

### ISSUE THREAD

**Issue by psolymos** [psolymos/abmispecies#22]
- [x] Incorporate text change suggestions sent by JS.
- [ ] add WestGrid/CC acknowledgement to birds, and multi-species pages.
- [x] update species models (2015 field data).
